### ISSUE TITLE
[1.18.2] [Suggestion] Add Forge tags to flowers

### ISSUE THREAD

**Issue by HalcyonSeas73** [xstarlotte/gardenaganzamain#1]
Gardenaganza version: 1.3
Forge version: 40.0.41
Minecraft version: 1.18.2

I would suggest adding tags, such as forge:flowers (I'm sure there are more/others), to flowers added by Gardenaganza; that way, mods that add Scythes (such as Cyclic) can harvest them (as they harvest based on those tags).

**Comment by xstarlotte** [comment]
Of course, I'll add tags to all the flowers later today! :)

**Comment by xstarlotte** [comment]
Hi! This has been done as of the new update (1.4). I hope this resolves all the issues to do with the flower tags!
