### ISSUE TITLE
[1.18.2] Updated Tags 2

### ISSUE THREAD

**Issue by HalcyonSeas73** [xstarlotte/gardenaganzamain#2]
You've released the 1.0.4 version on CurseForge, but not GitHub; regardless, loading the 1.0.4 version, Gardenaganza flowers don't show under the #flowers tag:
![Untitled](https://user-images.githubusercontent.com/84727791/162552604-400896f0-7064-4a68-ad25-569e2846ccc1.png)
![Untitled2](https://user-images.githubusercontent.com/84727791/162552708-cbbd1d37-9f20-4f58-bd42-d2307cf7c60b.png)

Perhaps I hadn't described the initial issue in enough detail; this is what i meant by adding tags to the flowers.

**Comment by xstarlotte** [comment]
Heya, the 1.5 version now adds the tags properly! #flowers will show all the Gardenaganza flowers ^-^ Thank you ~
