### ISSUE TITLE
[1.18.2] Flowers Not Dropping

### ISSUE THREAD

**Issue by HalcyonSeas73** [xstarlotte/gardenaganzamain#3]
Hello!

I've found that some naturally-generated flowers don't drop when broken, even by a silk touch tool:

- Tri-color Pansies
- White and Purple Pansies
- Sunrise Pansies
- Red Marigold
- Orange Marigold
- Yellow Marigold

Do they perhaps need Shears? If so, would there be a way to make that clear? Or perhaps on par with the other flowers?

**Comment by HalcyonSeas73** [comment]
A reminder/poke that this doesn't seem to be solved yet, @xstarlotte

**Comment by jltkerig** [comment]
There are missing loot tables (mod folder>data>gardenaanza>loot_tables>blocks) for the following: 
red_marigolds
orange_marigolds
yellow_marigolds

viola_tricolour_pansies
sunrise_pansies
white_purple_pansies
